name: k6 Load Tests

on:
  workflow_dispatch: # Manual trigger only

jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠️ Install k6
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates gnupg curl
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update && sudo apt-get install -y k6

      - name: 🚀 Run k6 Load Test
        run: k6 run load-test.js

      - name: 📤 Upload k6 Test Results
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: k6-results/
